### ISSUE TITLE
Lesscss is not working on Gradle 4.4.1

### ISSUE THREAD

**Issue by maximshe** [houbie/lesscss-gradle-plugin#5]
Hi,

I found that when I upgrade from Gradle 3.x to latest Gradle current lesscss is not working anymore.
```
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.tasks.DefaultTaskInputs.sourceDir() is applicable for argument types: (java.lang.String) values: [
src/main/webapp/css/less]
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.houbie.gradle.lesscss.SourceDirsTask.sourceDir(SourceDirsTask.groovy:71)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at build_69iuwkkafdzsik74bmucloxqy$_run_closure35.doCall(D:\projects\hera\src\hera\build.gradle:610)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:634)
09:38:33.852 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:86)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.tryInvokeMethod(DefaultNamedDomainObjectCollection.java:369)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:134)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:83)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at build_69iuwkkafdzsik74bmucloxqy.run(D:\projects\hera\src\hera\build.gradle:609)
09:38:33.853 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
```

Any thoughts?

**Comment by maximshe** [comment]
I found that `sourceDir` was deprecated since Gradle v.3.x see link below
`https://github.com/gradle/gradle/blob/v3.5.1/subprojects/core/src/main/java/org/gradle/api/tasks/TaskInputs.java#L148`

**Comment by maximshe** [comment]
See #6
